// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NvKPLGxQIh5eYjxS4neAEVrC_Qodjow',
    appId: '1:681788984200:web:5c296511c87424339f083d',
    messagingSenderId: '681788984200',
    projectId: 'budgetea-app',
    authDomain: 'budgetea-app.firebaseapp.com',
    storageBucket: 'budgetea-app.firebasestorage.app',
    measurementId: 'G-H6ZEXLBFYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAEAyhOFKfyd2WISkzy0H_8T9G2YanuXk',
    appId: '1:681788984200:android:8deabcfc71754fbc9f083d',
    messagingSenderId: '681788984200',
    projectId: 'budgetea-app',
    storageBucket: 'budgetea-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoCLEBUPgQjRzR2RaxZOLbWYJurvVJpp0',
    appId: '1:681788984200:ios:1121ad40f90dfdcd9f083d',
    messagingSenderId: '681788984200',
    projectId: 'budgetea-app',
    storageBucket: 'budgetea-app.firebasestorage.app',
    iosBundleId: 'com.example.budgeteaV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoCLEBUPgQjRzR2RaxZOLbWYJurvVJpp0',
    appId: '1:681788984200:ios:1121ad40f90dfdcd9f083d',
    messagingSenderId: '681788984200',
    projectId: 'budgetea-app',
    storageBucket: 'budgetea-app.firebasestorage.app',
    iosBundleId: 'com.example.budgeteaV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_NvKPLGxQIh5eYjxS4neAEVrC_Qodjow',
    appId: '1:681788984200:web:8b95db2bbe0eaa049f083d',
    messagingSenderId: '681788984200',
    projectId: 'budgetea-app',
    authDomain: 'budgetea-app.firebaseapp.com',
    storageBucket: 'budgetea-app.firebasestorage.app',
    measurementId: 'G-6XEMP3Z0KT',
  );
}
